version: '3'
services:

  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: GestionLocal
    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot service
  springboot-app:
    image: azyzbc/integratedprojects:1.0.2
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysql:3306/freelance?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
      tty: true
#"spring.datasource.password"=//lena zid mot de passe base de données si aandek mot de passe sinon fasakhha ligne hedhi//

volumes:
  mysql-data: