package com.example.user.Entities.freelance.enums;

public enum RefundOption {
    FIFTY_FIFTY,
    FAVORS_CUSTOMER,
    FAVORS_FREELANCER,
    WAIT_FOR_MORE_DAYS_AND_REDO_OPERATION,
    REQUIRES_THIRD_PARTY_INTERVENTION_OR_TICKET_RAISED,
    ALREADY_VALIDATED_AND_PAYED_WRONG_CALL,
    BAD_REQUEST

}
